### ISSUE TITLE
datasets (mp100)

### ISSUE THREAD

**Issue by xinkunwang111** [khoiucd/escape-tgt#1]
Could you please offer your datasets package? The mp100 is too complex to prepare and some instruction in[Pose-for-Everything](https://github.com/luminxu/Pose-for-Everything)'s github is wrong and unclear. 
Thank you!

**Comment by khoiucd** [comment]
Hi, thank you very much for your interests in our work. For the data, I just followed the guidance from Pose-for-Everything. If there are anythings unclear in preparing the data, please send me an email. I will try my best to help you.
