### ISSUE TITLE
GPU used for training and duration of the training

### ISSUE THREAD

**Issue by oopsRookie** [khoiucd/escape-tgt#2]
May I ask what GPU (brand, RAM size) was used for training, and how long did each split take?

**Comment by khoiucd** [comment]
Hi,

Thank you for your interests in our work. I used a single RTX 4090 (24Gb) for the training, and my machine has 64Gb RAM. I do not remember exactly but it tooks just a few hours to train one split.

Khoi

**Comment by oopsRookie** [comment]
Thank you a lot.



---- Replied Message ----
| From | Khoi Duc ***@***.***> |
| Date | 12/03/2024 02:00 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [khoiucd/escape-tgt] GPU used for training and duration of the training (Issue #2) |

Hi,

Thank you for your interests in our work. I used a single RTX 4090 (24Gb) for the training, and my machine has 64Gb RAM. I do not remember exactly but it tooks just a few hours to train one split.

Khoi
